### ISSUE TITLE
Startup Error: Property jgroups.s3.bucket_name could not be replaced as intended

### ISSUE THREAD

**Issue by tomkoufakis** [jgroups-extras/jgroups-aws#102]
I am trying to integrate this into a docker container but I cannot get a basic example working when using the infinispan docker image.

My setup is very vanilla.

**Dockerfile**:
`
FROM infinispan/server:12.1

USER root

COPY conf/ /opt/infinispan/server/conf/
COPY native-s3-ping-1.0.0.Final.jar /opt/infinispan/lib/native-s3-ping-1.0.0.Final.jar
CMD /opt/infinispan/bin/server.sh
`
Then in my /opt/infinispan/server/conf/infinispan.xml:

`
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:12.0 https://infinispan.org/schemas/infinispan-config-12.0.xsd
                            urn:infinispan:server:12.0 https://infinispan.org/schemas/infinispan-server-12.0.xsd
                            urn:infinispan:config:clustered-locks:12.0 https://infinispan.org/schemas/infinispan-clustered-locks-config-12.0.xsd
                            urn:org:jgroups https://www.jgroups.org/schema/jgroups-4.2.xsd"
        xmlns="urn:infinispan:config:12.0"
        xmlns:server="urn:infinispan:server:12.0"
        xmlns:locks="urn:infinispan:config:clustered-locks:12.0">

    <jgroups>
        <stack name="image-ec2" extends="ec2">
            <TCP bind_addr="${jgroups.bind.address,jgroups.tcp.address:0.0.0.0}"
                 bind_port="${jgroups.bind.port,jgroups.tcp.port:7800}"
                 enable_diagnostics="false"/>

            <org.jgroups.aws.s3.NATIVE_S3_PING
                region_name="us-west-2"
                bucket_name="infinispan"
                bucket_prefix="sdswrite-tomtest"/>

            
        </stack>

        <stack name="image-tcp" extends="tcp">
            <TCP bind_addr="${jgroups.bind.address,jgroups.tcp.address:0.0.0.0}"
                 bind_port="${jgroups.bind.port,jgroups.tcp.port:7800}"
                 enable_diagnostics="false"/>

            <MPING bind_addr="${jgroups.bind.address,jgroups.tcp.address:0.0.0.0}"/>
        </stack>

        <stack name="image-udp" extends="udp">
            <UDP enable_diagnostics="false"
                 port_range="0"
            />

            <FD_SOCK client_bind_port="57600" start_port="57600"/>
        </stack>

    </jgroups>

    <cache-container name="default" statistics="true" zero-capacity-node="false">
        <transport cluster="${infinispan.cluster.name:infinispan}" node-name="${infinispan.node.name:}"
        stack="image-udp"/>

        <distributed-cache name="hestia" statistics="true">
          <encoding media-type="application/x-protostream"/>
          <memory max-count="500000" when-full="REMOVE"/>
        </distributed-cache>

        <locks:clustered-locks num-owners="-1" reliability="CONSISTENT"/>
    </cache-container>

    <server xmlns="urn:infinispan:server:12.0">
        <interfaces>
            <interface name="public">
                <match-interface value="eth0"/>
            </interface>
        </interfaces>

        <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
            <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
        </socket-bindings>

        <security>
            <security-realms>
                <security-realm name="default">
                </security-realm>
            </security-realms>
        </security>

        <endpoints socket-binding="default" security-realm="default">
            <hotrod-connector />

                <rest-connector />

        </endpoints>

    </server>
</infinispan>
`

**Comment by belaban** [comment]
Looks like your config was not the actual one that's used: the default is
`<org.jgroups.aws.s3.NATIVE_S3_PING
      region_name="${jgroups.s3.region_name}"
      bucket_name="${jgroups.s3.bucket_name}"
      num_discovery_runs="3"
   />`

You may have to replace the existing discovery protocol.

But this is not the right place to ask; I suggest ask on the Infinispan mailing lists.
