### ISSUE TITLE
KMS encryption does set the appropriate request headers

### ISSUE THREAD

**Issue by kherock** [jgroups-extras/jgroups-aws#313]
It appears that potentially after the upgrade to the AWS SDK v2, the request to S3 is lacking the necessary headers to actually enable encryption using the specified KMS key. Based on some rudimentary testing using Bucket policies asserting headers, it seems like the `x-amz-server-side-encryption: aws:kms` header is missing. This can be done in the new SDK by specfying

```java
putRequestBuilder.serverSideEncryption(ServerSideEncryption.AWS_KMS);
```

https://github.com/jgroups-extras/jgroups-aws/commit/8c4e3a367d9ea16b83ad1ca04a1e0ea747cf55c4#diff-544667907d20fc0bef7bdc8513cd3fdd714c2ddc977d86a311f0aa7514dc7f1fR231-R232

I haven't had an opportunity to test this as a potential fix, however.

**Comment by rhusar** [comment]
Thanks for the report @kherock, I ll try to have a look in the coming days, if you get to test the fix, contribution would be ideal!

**Comment by rhusar** [comment]
Opened PR https://github.com/jgroups-extras/jgroups-aws/pull/384
