### ISSUE TITLE
What is the time scale for the 0.9.4 release?

### ISSUE THREAD

**Issue by SBrown52** [jgroups-extras/jgroups-aws#5]
Hi,

When will 0.9.4 be released? Is there any help you need in releasing it?

Thanks,
Sam

**Comment by belaban** [comment]
What's new that you want a release? I could do this after Easter if needed...

**Comment by SBrown52** [comment]
The upgraded versions of the aws-sdk. I can not use the currently released version on mvn cental (0.9.3.Final).

**Comment by belaban** [comment]
OK, released 0.9.4.Final
