### ISSUE TITLE
Only include necessary aws libraries

### ISSUE THREAD

**Issue by aheintz** [jgroups-extras/jgroups-aws#8]
I'm using JGroups and native-s3-ping in a project and found that the application grew a lot. We discovered that native-s3-ping includes the entire aws-java-sdk but only relies on the aws-java-sdk-core and aws-java-sdk-s3 (which implicitly includes aws-java-sdk-core, but for clarity I added both the core and s3 dependency).

I created a pull request and would appreciate if that could be merged and released (if acceptable) since that would reduce the size of our app with >100Mb. https://github.com/jgroups-extras/native-s3-ping/pull/7

**Comment by belaban** [comment]
I applied your PR and released 0.9.5.Final
